import os

ROOT_BUFFER_DIR = "../buffer"
BUCKET_NAME = "test"
MINIO_ENDPOINT = 'localhost:9000'
MINIO_ACCESS_KEY = 'tgm3hgLX5uSxKIqecX3R'
MINIO_SECRET_KEY = 'o4CkZ0GOqCVISRbxYRdaG99miSBJlaQv87cfwOAO'
SSL_FLAG = False
THREADS_NUMBER = 5
RABBITMQ_USERNAME = 'guest'
RABBITMQ_PASSWORD = 'guest'
RABBITMQ_HOST = 'localhost'
RABBITMQ_EXCHANGE = 'test'
RABBITMQ_EXCHANGE_TYPE = 'direct'
RABBITMQ_EXCHANGE_DURABLE = True
RABBITMQ_QUEUE = 'test'
RABBITMQ_QUEUE_DURABLE = True
ROUTING_KEY = 'a'
RABBITMQ_QUEUE_RESULT = 'result'
RABBITMQ_QUEUE_RESULT_DURABLE = True
ROUTING_KEY_RESULT = 'b'
CONVERSION_ATTEMPTS = 5


# ROOT_BUFFER_DIR = os.getenv('ROOT_BUFFER_DIR')
# BUCKET_NAME = os.getenv('BUCKET_NAME')
# MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT')
# MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY')
# MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY')
# SSL_FLAG = os.getenv('SSL_FLAG')
# THREADS_NUMBER = os.getenv('THREADS_NUMBER')
# RABBITMQ_USERNAME = os.getenv('RABBITMQ_USERNAME')
# RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD')
# RABBITMQ_HOST = os.getenv('RABBITMQ_HOST')
# RABBITMQ_EXCHANGE = os.getenv('RABBITMQ_EXCHANGE')
# RABBITMQ_EXCHANGE_TYPE = os.getenv('RABBITMQ_EXCHANGE_TYPE')
# RABBITMQ_EXCHANGE_DURABLE = os.getenv('RABBITMQ_EXCHANGE_DURABLE')
# RABBITMQ_QUEUE = os.getenv('RABBITMQ_QUEUE')
# RABBITMQ_QUEUE_DURABLE = os.getenv('RABBITMQ_QUEUE_DURABLE')
# ROUTING_KEY = os.getenv('ROUTING_KEY')
# RABBITMQ_QUEUE_RESULT = os.getenv('RABBITMQ_QUEUE_RESULT')
# RABBITMQ_QUEUE_RESULT_DURABLE = os.getenv('RABBITMQ_QUEUE_RESULT_DURABLE')
# ROUTING_KEY_RESULT = os.getenv('ROUTING_KEY_RESULT')
# CONVERSION_ATTEMPTS = os.getenv('CONVERSION_ATTEMPTS')
