ROOT_BUFFER_DIR = "../buffer"
BUCKET_NAME = "test"
MINIO_ENDPOINT = 'localhost:9000'
MINIO_ACCESS_KEY = 'tgm3hgLX5uSxKIqecX3R'
MINIO_SECRET_KEY = 'o4CkZ0GOqCVISRbxYRdaG99miSBJlaQv87cfwOAO'
SSL_FLAG = False
THREADS_NUMBER = 5